- alias: test
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: h34-ablation65-stg
  name: h34-ablation65-stg
  services: null
- alias: hasura
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: h34-calk15-stg
  name: h34-calk15-stg
  services: null
